version: 0.0
os: linux
files:
   - source: /target/jboss-helloworld.war
     destination: /opt/wildfly/standalone/deployments
hooks:
  BeforeInstall:
    - location: codeDeployFolder/stopServer.sh
      runas: root
  AfterInstall:
    - location: codeDeployFolder/startServer.sh
      runas: root
